<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <Compile Remove="Areas\User\Views\Book\**" />
    <Content Remove="Areas\User\Views\Book\**" />
    <EmbeddedResource Remove="Areas\User\Views\Book\**" />
    <None Remove="Areas\User\Views\Book\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZahrawyAirFly.Infrastructure\ZahrawyAirFly.Infrastructure.csproj" />
    <ProjectReference Include="..\ZahrawyAirFly.Shared\ZahrawyAirFly.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Stripe.net" Version="52.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\img\Aircrafts\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e211189d-dc1d-452b-beef-6617fd2919b2</UserSecretsId>
  </PropertyGroup>

</Project>
